### PR TITLE
Added publishers of masterboard and robot mode

### PR DESCRIPTION
**Pull request by akihikoy**
Added publishers of masterboard data (ur_driver/masterboard_state)
and robot mode data (ur_driver/robot_mode_state).
The type of ur_driver/masterboard_state is ur_msgs/MasterboardDataMsg,
while the type of ur_driver/robot_mode_state is ur_modern_driver/RobotModeDataMsg;

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Hi, thanks for the PR.

Can you please tell us a little about your rationale for adding this?

Also: the messages are already available in the `ur_msgs` package. Let's not copy the files, but just use those in `ur_msgs`.

**Comment by akihikoy** [comment]
Thanks for reviewing.
The reason I added robot_mode_state is that I wanted to know the robot state such as "the robot is protective stopped" from a ROS node.  As far as I understand, the only way to know such a state is using the follow_joint_trajectory topic, but it is not good.

Regarding masterboard_state, I will not use it at this moment, but I thought that it would be useful.

I reviewed the ur_msgs where I found the MasterboardDataMsg message (so I am using it, of course), but I did not find RobotModeDataMsg or similar messages.  Could you indicate an adequate message that I should use?

**Comment by ipa-nhg** [comment]
what about move the `RobotModeDataMsg.msg` to `ur_mgs ` ? I think that at least for consistency reasons, make sense

**Comment by gavanderhoorn** [comment]
This PR has an analogue/replacement in Zagitta/ur_modern_driver#27. We should probably port that one.

**Comment by gavanderhoorn** [comment]
With the merge of #247 we now have support for this in `kinetic-devel`.

**Comment by gavanderhoorn** [comment]
Thanks again @akihikoy for the PR.

Closing.

**Pull request closed without merging**
