### PR TITLE
URe Support

### PR DESCRIPTION
**Pull request by dniewinski**
Added support for URE series.  Tested on UR5E 5.0.0 and UR5 3.5.3.  Requires https://github.com/ros-industrial/universal_robot/pull/380 (approved but not merged yet)

### CODE REVIEW

**Comment by geg58** [comment]
> As a note to those testing, in the URE, you have to enable Remote Control (Menu > Settings > System > Remote Control > Enable) then switch to Remote Control with the new button in the top right

were you able to connect to a real robot? I keep getting connection refused. is there a different ur_bringup launch file for the e-series? I dont see one.

**Comment by dniewinski** [comment]
@geg58 I tested with a real UR5 and UR5E.  To do the initial connection and monitoring, you shouldn't need to enable the Remote Control, that is only if you are commanding motion.  Ensure your IP and Subnet are set correctly in your computer and on the UR controller.

**Comment by happygaoxiao** [comment]
@dniewinski Hello, I have a real UR5e robot. Do you have coded a ROS driver for UR5e? Thanks for your help.

**Comment by dniewinski** [comment]
@happygaoxiao This PR is to add that support.  Clone my fork and the ur_e branch from my fork of universal_robot and it should work

**Comment by geg58** [comment]
> @happygaoxiao This PR is to add that support. Clone my fork and the ur_e branch from my fork of universal_robot and it should work

I got both of these going, but had to run the ur_e_description as well in order for it to all work. gazebo simulation wasnt able to update from joint states in rviz for me however - I'll try to debug and post an update.

**Comment by happygaoxiao** [comment]
@dniewinski  Hello, I seem not to understand what you said. Do you mean you test in the rivz for path planning and in the gazebo for simulation?. Have you ever tested your driver in the off-line simulator from [UR Sim](http://www.universal-robots.com/download/?option=45449#section41511) or the real robot? I want to control the robot in real-time 500Hz at the [remote control](http://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/remote-control-via-tcpip-16496/) and get the robot state(such as joint states). 
      I have downloaded your package at the `ur_e` branch. But the data unpacking operation was written several years ago, which is different from the new robot in [Client_Interface_V3.7andV5.1.xlsx](http://www.universal-robots.com/how-tos-and-faqs/how-to/ur-how-tos/remote-control-via-tcpip-16496/). @geg58, I launched these `.launch` files but not topic is relate to robot state in the offline simulator. How did you connect to the [offline simulato](http://www.universal-robots.com/download/?option=45449#section41511)r? Maybe I do something wrong for my poor programming skills.

**Comment by AustinDeric** [comment]
I am unable to stream correct joint_states with our ur10e. 

launch file:
```
<launch>
  <arg name="robot_ip" default="192.168.32.29" />
  <include file="$(find ur_modern_driver)/launch/ur10e_bringup_joint_limited.launch">
    <arg name="robot_ip" value="$(arg robot_ip)" />
  </include>
</launch>
```

ur_modern_driver output:
```
NODES
  /
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    ur_driver (ur_modern_driver/ur_driver)

auto-starting new master
process[master]: started with pid [24674]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1f5247dc-d3e8-11e8-9e5d-d46a6a72bdd1
process[rosout-1]: started with pid [24687]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [24703]
process[ur_driver-3]: started with pid [24705]
[ INFO] [1539985455.633114555]: Setting up connection: 192.168.32.29:30003
[ INFO] [1539985455.634013892]: Connection established for 192.168.32.29:30003
[ INFO] [1539985455.634048341]: Setting up connection: 192.168.32.29:30001
[ INFO] [1539985455.634406843]: Connection established for 192.168.32.29:30001
[ INFO] [1539985456.122771086]: Got VersionMessage:
[ INFO] [1539985456.122817956]: project name: URControl
[ INFO] [1539985456.122839889]: version: 5.1.0
[ INFO] [1539985456.122858795]: build date: 13-08-2018, 06:37:36
[ INFO] [1539985456.122878622]: Disconnecting from 192.168.32.29:30001
[ INFO] [1539985456.145725981]: ActionServer enabled
[ INFO] [1539985456.145839812]: Use standard trajectory follower
[ INFO] [1539985456.150687329]: Setting up connection: :50001
[ INFO] [1539985456.151025525]: Connection established for :50001
[ INFO] [1539985456.151250655]: Initializing ur_driver/URScript subscriber
[ INFO] [1539985456.162271526]: The ur_driver/URScript initialized
[ INFO] [1539985456.162372190]: Notifier: Pipeline disconnect will shutdown the node
[ INFO] [1539985456.171320044]: Service 'ur_driver/robot_enable' activation mode: Never
[ INFO] [1539985456.171431378]: Starting main loop
[ INFO] [1539985456.171678158]: Setting up connection: 192.168.32.29:30003
[ INFO] [1539985456.171767861]: Starting pipeline RTPacket
[ INFO] [1539985456.171947456]: Starting pipeline StatePacket
[ INFO] [1539985456.172081742]: Setting up connection: 192.168.32.29:30002
[ INFO] [1539985456.173161873]: Connection established for 192.168.32.29:30002
[ INFO] [1539985456.173345630]: Connection established for 192.168.32.29:30003
[ INFO] [1539985456.175836298]: Starting ActionServer
[ INFO] [1539985456.176157517]: Trajectory thread started
```

rostopic echo /joint_states:
```
header: 
  seq: 4790
  stamp: 
    secs: 1539985391
    nsecs: 114175471
  frame_id: ''
name: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint,
  wrist_3_joint]
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
image

remote control enabled or disabled doesn't seem to have any effect.

I would love to get our e-series working so anything i can so, please let me know!

**Comment by dniewinski** [comment]
@AustinDeric If you are seeing all zeroes for joint angles, but no errors in your terminal, it likely means the arm itself hasn't been started.  In the new version of the Polyscope software, it doesn't seem to make you start the arm by default when the controller starts.  You should see a green circle in the bottom-left of the UR screen.  If you don't, press the circle and go through the steps to start and calibrate the arm and those joint angles should come up.  

Once that is done, see my comment above about enabling remote control so you can move the arm, not just monitor it

**Comment by dniewinski** [comment]
@happygaoxiao This driver works for connecting to a real robot arm, and that is what I used for testing.  It should also work the same when running it with the URCap SDK simulator, but I didn't test this.  If you are running the Gazebo simulation, you don't need to use this driver

**Comment by happygaoxiao** [comment]
@dniewinski  Thanks for your reply. Could you tell me how to use your driver?  There is no URe `.launch` file. I test the ur5_bringup.launch but get some errors: 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/gx/catkin_ws/src/universal_robot-ur_e/ur_driver/src/ur_driver/driver.py", line 274, in __run
    self.__on_packet(packet)
  File "/home/gx/catkin_ws/src/universal_robot-ur_e/ur_driver/src/ur_driver/driver.py", line 186, in __on_packet
    state = RobotState.unpack(buf)
  File "/home/gx/catkin_ws/src/universal_robot-ur_e/ur_driver/src/ur_driver/deserialize.py", line 324, in unpack
    raise Exception("Fatal error when unpacking RobotState packet")
Exception: Fatal error when unpacking RobotState packet
````
For the testRT_comm.py, it shows: `RobotStateRT has wrong length: 1108`.  So could you show me how to bring up the UR e-Series robot?

**Comment by gavanderhoorn** [comment]
> @dniewinski Thanks for your reply. Could you tell me how to use your driver? There is no URe `.launch` file.

Are you sure you are using the `kinetic-devel` branch of @dniewinski's fork?

That is where the e-series changes are in.

And there are e-series launch files as well, see [here](https://github.com/dniewinski/ur_modern_driver/tree/818f579c1a5c73f2ca7b3afaf658609656f0530f/launch). But they don't magically change the driver, they wouldn't even really be needed.

**Comment by dniewinski** [comment]
@happygaoxiao I'm glad to hear that the driver is working with 5.1!  I would recommend using Kinetic with the current version of the driver.  

This PR is aimed at adding support for the latest UR software.  Unfortunately, I think the tracking performance is a little outside of the scope of this PR and should likely be handled elsewhere.  @gavanderhoorn ?

**Comment by happygaoxiao** [comment]
@dniewinski  Could your please tell me what can I  do for this problem ? I have no idea about this.
> (1) When I run roslaunch ur_modern_driver ur5e_ros_control.launch , the robot moves at a very high speed to joint_states.position = [0,0,0,0,0,0]. It's so scaring.

In addition, I will improve the PID parameters or use the `servoj` script to design a feedback controller, for a  better tracking performance.

**Comment by miguelprada** [comment]
@happygaoxiao you may be hitting the issue described in #206. Can you try the fix proposed in #213?

**Comment by AustinDeric** [comment]
I successfully was able to pass a trajectory to the UR10e using moveit.  The robot executed the trajectory, but the result was not as expected.  The robot overshoots  the goal. 

actual video:
https://youtu.be/7hVw656VKXw

rviz:
https://youtu.be/9qvoe9U74yY

Here is the log from `rostopic echo /move_group/goal `
https://gist.github.com/AustinDeric/1d316001b601bfcaaadf36ad46be592e

Here is the log from `rostopic echo /follow_joint_trajectory/goal`:
https://gist.github.com/AustinDeric/03f9125c0c11f20c1e17e1efd21308b1

To recreate:
in terminal 1:
```
roslaunch ur_modern_driver ur10e_bringup.launch robot_ip:=192.168.32.29
```
in terminal 2:
```
roslaunch ur10_e_moveit_config ur10_e_moveit_planning_execution.launch
```
in terminal 3:
```
roslaunch ur10_e_moveit_config moveit_rviz.launch
```

After an execution, if replan and then execute, i will get the following error:
```
Invalid Trajectory: start point deviates from current robot state more than 0.01
joint 'elbow_joint': expected: 0.567835, current: -0.622903
```
but it may be nothing

```

**Comment by brianzhang-git** [comment]
> I got both of these going, but had to run the ur_e_description as well in order for it to all work. Sim works great, have to have 4 terminals: 1 for ur_e_description, 1 for ur_e_gazebo, 1 for ur_e_movit_config, 1 for moveit rviz. Awesome @dniewinski thanks for getting this all going

Hi @geg58, I'm trying to follow what you've done and running into a bit of a problem. I have the following things going:
ur_e_gazebo ur5e.launch
ur5_e_moveit_config ur5_e_moveit_planning_execution.launch sim:=true
ur5_e_moveit_config moveit_rviz.launch

When I try to run ur_e_description ur5e_upload.launch, it says that there are no processes to monitor and stops. However, it doesn't seem related to my error:

In Rviz, I can plan a movement, but it fails when attempting to execute. In the console for ur5_e_moveit_planning_execution.launch, I see:
> [ERROR] [1540860321.447192390, 2083.033000000]: Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]
> [ERROR] [1540860321.447275983, 2083.033000000]: Known controllers and their joints:

In the startup sequence, there are the following errors/warnings:

> [ WARN] [1540858218.000130178, 26.131000000]: Waiting for /follow_joint_trajectory to come up
> [ WARN] [1540858224.009196790, 32.131000000]: Waiting for /follow_joint_trajectory to come up
> [ERROR] [1540858230.018252366, 38.131000000]: Action client not connected: /follow_joint_trajectory
> [ INFO] [1540858230.095139068, 38.208000000]: Returned 0 controllers in list
> [ INFO] [1540858230.112521862, 38.226000000]: Trajectory execution is managing controllers

> [ERROR] [1540858230.144966664, 38.258000000]: Exception while loading move_group capability 'move_group/MoveGroupExecuteService': MultiLibraryClassLoader: Could not create class of type move_group::MoveGroupExecuteService
> Available capabilities: move_group/ApplyPlanningSceneService, move_group/ClearOctomapService, move_group/MoveGroupCartesianPathService, move_group/MoveGroupExecuteService, move_group/MoveGroupExecuteTrajectoryAction, move_group/MoveGroupGetPlanningSceneService, move_group/MoveGroupKinematicsService, move_group/MoveGroupMoveAction, move_group/MoveGroupPickPlaceAction, move_group/MoveGroupPlanService, move_group/MoveGroupQueryPlannersService, move_group/MoveGroupStateValidationService

> [ INFO] [1540860316.795162190, 2078.414000000]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
> Check clock synchronization if your are running ROS across multiple machines!
> [ WARN] [1540860316.795212990, 2078.414000000]: Failed to fetch current robot state.

Would you (or anyone) be able to point me in the right direction? Thanks!

**Comment by happygaoxiao** [comment]
Hello @AustinDeric，your video is a little strange. Have you check your trajectory? I have used dniewinski's driver and it works fine.  I  have launched the `ur5e_bringup.launch` and `ur5_e_moveit_planning_execution.launch` for an eye-hand calibration. It moves smooth and exactly to the goal.

@brianzhang-git Have you installed the` joint-coontrollers`?

**Comment by dniewinski** [comment]
@AustinDeric Might sound like a silly question, but on the UR controller, is the motion speed slider in the bottom of the UR interface set to 100%?

**Comment by AustinDeric** [comment]
@dniewinski i set the speed to 10% for safety reasons.

@happygaoxiao good to know, thanks!

**Comment by dniewinski** [comment]
@AustinDeric I can see that being the issue.  Try increasing the controller speed to 100% and see if it fixes the issue.  If it does, you can limit the speed of the motion in the robot's description and MoveIt! config.

**Comment by AustinDeric** [comment]
@dniewinski making the velocity and acceleration scaling factor 0.2 worked perfectly.

+1 from me, tested and working.

**Comment by brianzhang-git** [comment]
Hello! Running into an error connecting to a UR5e via `roslaunch ur_modern_driver ur5e_bringup.launch` that's identical to issue [#136](https://github.com/ros-industrial/ur_modern_driver/issues/136). According to that thread, it seems that it's issues with the binary stream and the deserializer on URSoftware's side and is sometimes fixed by updating. I've run on versions 5.1.1.X and 5.2.0.X. Has anyone tried on these versions? It seems like the @dniewinski has been running on 5.0.X and @AustinDeric on 5.1.0.X. My next step is to try re-imaging back to 5.1.0.X since its the earliest available.

**Comment by Joinyong** [comment]
@dniewinski Hello! I have the same problem with @happygaoxiao. And  when I run _roslaunch ur_modern_driver ur5e_ros_control.launch_ , the robot moves at a very high speed to joint_states.position = [0,0,0,0,0,0]. Do you have any idea about it? Thanks a lot!

**Comment by happygaoxiao** [comment]
Hello @dniewinski ，If I use the `ur5e_bringup.launch`，the robot works fine and smoothly. It adopts the client of `\follow_joint_trajectory`.

But if I use the `ros_control` launch file, The UR5e will move to all zero joint_state in a high speed. I mean the robot moves as long as I launch the `ur5e_roscontrol.launch` file. I hope to do the real-time control at 500Hz.  That strange thing shouldn't happen, since I have not launched any nodes. 
Could you please give me some help. I have test in the indigo and kinetic ROS version. And I just don't know why this could happen.

**Comment by miguelprada** [comment]
@happygaoxiao your issue seems to be the one described in #206, which was fixed in #213, which was merged at 2f1251c. Unfortunately, this commit is posterior to the point where @dniewinski branched off for the URe modifications.

Can you try to merge `ros-industrial:kinetic-devel` into `dniewinski:kinetic-devel` locally and see if that fixes the issue for you? If that's the case, it may make sense to rebase this PR so that this issue is also fixed here.

**Comment by miguelprada** [comment]
So I finally got my hands on a UR5e and have been trying this version of the driver (after merging `ros-industrial/kinetic-devel` into this branch, to avoid #206).

First comment is that the driver mostly works with our robot, which is running 5.2.0.61336. Nice work, @dniewinski!

The not so good new is that some quick tests using the `vel_based_pos_traj_controller` show terrible performance. I was afraid this could be the case, and I attribute the problems to the fact that this mode is sending one line scripts at each control loop iteration, as opposed to the single script + reverse socket approach which is used when working with the position interface (or the non-`ros_control` modes, for that matter). This worked fine at 125Hz but not so much at 500Hz, possibly because the controller is not able to keep up parsing/compiling scripts at this rate.

One thing I'd like to try is to re-implement the velocity interface code path in a similar manner to the position interface path, i.e. uploading a single _master_ script that receives velocity values and executes `speedj` commands in a loop. I won't be able to work much on this until at least one week from now, so if anyone is willing to contribute in this direction, please let me know.

Also, I'm curious whether @ThomasTimm or @Zagitta can comment on the reasons why these two modes are implemented so differently. Do you think there's any fundamental reason why the change I suggest above will not work?

**Comment by happygaoxiao** [comment]
@miguelprada  Thanks for your help. We have tested the driver in `pos_based_pos_traj_control` at 500Hz. I am happy to say it works fine! But I am just wondering if the real-time tracking performance could be better. Probably due to the _lookahead_ time in the `servoj` script, there is a _100ms_ delay for real-time trajectory tracking. `speedj` is expected to have a lower delay.

I used to test Thomas in UR5 and UR3 (3.3 or 3.4 version) last year. The `servoj` client works fine at 125Hz. But `speedj` is not stable and shows terrible tracking performance.
I will test the `speedj` in UR5e two days later. Please keep in contact. Thanks a lot.

**Comment by dniewinski** [comment]
Rebased

**Comment by ChunJyeBehBeh** [comment]
Hello,

I have testing the ur_modern_driver which download from this [link](https://github.com/dniewinski/ur_modern_driver).

I want to run the real world UR5e robotics arm with my Ubuntu 16.04 ros Kinetic framework.

This is the command I run in different terminal.
```
>>roslaunch ur_description ur5_upload.launch
>>roslaunch ur_modern_driver ur5e_bringup.launch robot_ip:=192.168.1.150
```

`>>roslaunch ur_modern_driver ur5e_bringup.launch robot_ip:=192.168.1.150`

> [ INFO] [1551948471.412181675]: Loading robot model 'ur5e'...
> [ WARN] [1551948471.412244966]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
> [ INFO] [1551948471.412261449]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [ INFO] [1551948471.887345150]: Loading robot model 'ur5e'...
> [ WARN] [1551948471.887415949]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
> [ INFO] [1551948471.887450574]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [ INFO] [1551948472.026621472]: Publishing maintained planning scene on 'monitored_planning_scene'
> 

`>>roslaunch ur5_moveit_config moveit_rviz.launch config:=true`

> [ERROR] [1551949536.231887280]: No robot state or robot model loaded
> [ INFO] [1551949536.236069906]: Loading robot model 'ur5e'...
> [ WARN] [1551949536.236114993]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
> [ INFO] [1551949536.236128787]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [ INFO] [1551949536.284219417]: Loading robot model 'ur5e'...
> [ WARN] [1551949536.284248174]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
> [ INFO] [1551949536.284258547]: No root/virtual joint specified in SRDF. Assuming fixed joint
> [ INFO] [1551949536.361852337]: Starting scene monitor
> [ INFO] [1551949536.365366772]: Listening to '/move_group/monitored_planning_scene'
> [ INFO] [1551949536.810248478]: Constructing new MoveGroup connection for group 'manipulator' in namespace ''
> [ WARN] [1551949537.619982832]: 
> Deprecation warning: Trajectory execution service is deprecated (was replaced by an action).
> Replace 'MoveGroupExecuteService' with 'MoveGroupExecuteTrajectoryAction' in move_group.launch
> [ INFO] [1551949537.631355072]: Ready to take commands for planning group manipulator.
> [ INFO] [1551949537.631549401]: Looking around: no
> [ INFO] [1551949537.631647323]: Replanning: no
> [ WARN] [1551949537.651003025]: Interactive marker 'EE:goal_ee_link' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.
> [ INFO] [1551949542.332149068]: Stopping scene monitor
> [ INFO] [1551949542.334702244]: Starting scene monitor
> [ INFO] [1551949542.344621091]: Listening to '/planning_scene'

I get few warning after I run the command. I try to plan and execute within the RVIZ but the robotics arm is not moving. May I know how to solve it?

screenshot from 2019-03-07 17-06-38

**Comment by martimorta-wood** [comment]
Hi, are you launching the upload before the bringup? If so, you shouldn't. Try following the [Usage](https://github.com/dniewinski/ur_modern_driver#usage)

> ```
> >>roslaunch ur_description ur5_upload.launch
> >>roslaunch ur_modern_driver ur5e_bringup.launch robot_ip:=192.168.1.150
> ```

Also you are calling ur5 launches, it should be ur5_e_moveit_config

> ```roslaunch ur5_moveit_config moveit_rviz.launch config:=true```

You need the latest version of https://github.com/ros-industrial/universal_robot branch Kinetic devel to have the e series packages.

I hope it helps.

**Comment by ChunJyeBehBeh** [comment]
Hi @martimorta-wood , I follow your solution and all things are good although there is warns after I run the last command.

Here is the commands I run in different terminal:
```
roslaunch ur_modern_driver ur5e_bringup.launch robot_ip:=192.168.1.150
roslaunch ur5_e_moveit_config ur5_e_moveit_planning_execution.launch 
roslaunch ur5_e_moveit_config moveit_rviz.launch config:=true
```

Now the problem is after I plan and execute,
It show it Uploading trajectory program to robot but no further action has been executed to the robot.

t

Is there any wrong with my setup? How can I solve it?

**Comment by dniewinski** [comment]
@ChunJyeBehBeh Make sure your controller has Remote Control enabled.  It is in the settings menu.  Here is a link to a tutorial I wrote about it if you need an explanation: http://www.clearpathrobotics.com/assets/guides/ur/ur_e_setup/controller.html

**Comment by ChunJyeBehBeh** [comment]
@dniewinski I have enabled the remote control already but it stuck at "Uploading trajectory program to robot"

I have connect the ur5e to a router and at the same time I connect my laptop to that router with a Ethernet cable.

whatsapp image 2019-03-08 at 10 25 50

**Comment by martimorta-wood** [comment]
In rviz moveit try reducing speed and acceleration scale to something like 0.05 and see if it works.

**Comment by dniewinski** [comment]
@ChunJyeBehBeh In your image, you have enabled the display of the selection, but you haven't set the robot to remote control.  In the menu you have pressed, you need to then select Remote Control.  The image on the top bar will change from the pendant to the 2 boxes connected with a line.  Once this is done, restart the ROS nodes and try again

**Comment by brianjohnzhang** [comment]
@ChunJyeBehBeh I just solved this problem by opening port 50001 on my computer. It seems that the Polyscope attempts to connect on this port, not sure if this is possible to detect/throw as an error message through the package?

**Comment by miguelprada** [comment]
I'd like to start moving this forward again, but I think there are some issues to deal with before being able to merge.

First, there's a couple simple inconsistencies between the CB and e-series launchfiles:

- When you last rebased, @dniewinski, the base of your branch went from before to after #236, where some new arguments were added to the `ros_control` launchfiles
- Similar to the above, shortly after your branch diverges from it, #254 was merged into `kinetic-devel`, which also adds arguments to all launchfiles

Could you please add the same argument to the e-series launchfiles?

Then there's the bigger issue of the `ros_control` velocity interface not working properly on the e-series. I've had the chance to work on this a little bit and I think I managed to implement the solution I suggested in [this comment](https://github.com/ros-industrial/ur_modern_driver/pull/216#issuecomment-453175617). You can see the changes I based on top of this branch in the [ur-e branch in my fork](https://github.com/miguelprada/ur_modern_driver/tree/ur-e).

So far I've only been able to run a few tests on a UR5e, which look promising, but I'd like to test I didn't break the functionality for the CB series as well. I can check with a UR5 running 3.5.something, but it would be great if other people can test with other robots and PolyScope versions.

At this point I'm unsure how to proceed. We can either merge this PR with velocity interface not working and let me rebase my changes and open a new PR, or fast-forward this PR to include my changes and review everything as a whole. Please keep in mind that my changes have not been thoroughly tested and may break existing functionality.

What do you think, @dniewinski, @gavanderhoorn, @ipa-nhg?

**Comment by dniewinski** [comment]
@miguelprada I will make the changes to the launch files for the missing arguments.
As far as the velocity interface issue, I think it would be more complete/proper to include your fixes, but that also opens up the possibility of this merge taking much longer.

**Comment by miguelprada** [comment]
> @miguelprada I will make the changes to the launch files for the missing arguments.

Thanks! There were some tabs instead of spaces there, but I took the liberty to fix that.

> As far as the velocity interface issue, I think it would be more complete/proper to include your fixes, but that also opens up the possibility of this merge taking much longer.

Indeed. But merging this with a not functional `ros_control` velocity interface is not ideal either. An intermediate option is to merge it adding some kind of warning/error to the user that the mode is not supported. This would allow to have _some_ support for e-series right now and leave the other set of changes for a separate discussion. I'd really like the input of the other maintainers, @gavanderhoorn, @ipa-nhg?

**Comment by ipa-nhg** [comment]
I don't have any problem merging this if the node gives an error for the velocity interface. Although I think it is a big issue, but I understand that solve it is hard an will delay the merge.

A third option that we have is create a new branch for the E-Series, not ideal but at least using a branch for the upstream repository (and linking the branch on the readme of master branch) we have a common branch to submit PRs.

**Comment by tkelestemur** [comment]
Is there any update on this? 

I can confirm that @dniewinski 's fork works with UR3e on Ubuntu 16.04 and Kinetic. The UR software version is 5.3.X.X. I had the error mentioned in this [issue](https://github.com/ros-industrial/ur_modern_driver/issues/136) with current `kinetic-devel` branch.

**Comment by miguelprada** [comment]
I cherry-picked #269 and fixed a small formatting issue. This should (hopefully) allow the CI checks to pass.

**Comment by miguelprada** [comment]
I pushed a commit to [disable-velocity-iface](https://github.com/miguelprada/ur_modern_driver/tree/disable-velocity-iface) branch in my fork with the proposal to temporarily disable the `ros_control` velocity interface for the URe series. Being a single commit, I think it should be easily reverted.

@gavanderhoorn, @ipa-nhg, would you rather keep this open and try to merge only when the full functionality is there or should we push that commit to this branch and merge? I'm not sold on creating yet another branch for the e-series.

**Comment by ipa-nhg** [comment]
@miguelprada I vote for merge, adding some lines to the Readme about the limitation of the support for URe

**Comment by gavanderhoorn** [comment]
@miguelprada wrote:
> would you rather keep this open and try to merge only when the full functionality is there or should we push that commit to this branch and merge? I'm not sold on creating yet another branch for the e-series.

I'm not a fan of the duplicated launch files (just as I wasn't too happy with all the duplicated packages in `universal_robot`), but it makes sense to merge this first and do cleanup later.

re: `ros_control` problem: I suggest we remove the `ros_control` related launch file(s) for the e-series for now, that should give a (first) indication that `ros_control` is currently not supported with e-series controllers. As @ipa-nhg suggests, we also clearly document this. That would be a second indication that `ros_control` is not supported at the moment.

If/when fixed, we'll update the documentation and add the appropriate launch file.

I'd like to keep history in tact for this one (so no squash-merge), but am unsure about the last two commits by @miguelprada.

**Comment by miguelprada** [comment]
> I'm not a fan of the duplicated launch files (just as I wasn't too happy with all the duplicated packages in universal_robot), but it makes sense to merge this first and do cleanup later.

A minimum of 6 separate launch files for each model (3xCB and 3xe) are needed in order to load the proper URDF models. However, the number of launch files per model could be reduced at the cost of adding one (or more?) extra argument(s). This can be dealt with later, though.

> re: ros_control problem: I suggest we remove the ros_control related launch file(s) for the e-series for now, that should give a (first) indication that ros_control is currently not supported with e-series controllers. As @ipa-nhg suggests, we also clearly document this. That would be a second indication that ros_control is not supported at the moment.
> 
> If/when fixed, we'll update the documentation and add the appropriate launch file.

Not a big fan of removing the launch files since:

- position interface seems to work just fine
- one can still try to use the velocity interface, either through the CB launch files or using custom ones

I understand that the _hack_ I proposed [above](https://github.com/ros-industrial/ur_modern_driver/pull/216#issuecomment-478547699) is far from ideal, but it would be my preferred choice.

> I'd like to keep history in tact for this one (so no squash-merge), but am unsure about the last two commits by @miguelprada.

Note sure what can be done about these. They are required for the travis checks to pass, but I won't complain if they are removed and the PR is _force-merged_.

One last thing. I've just found out that with the default `ros_control` controller configuration the driver is not publishing data from the e-series as fast as it can (e.g. see [this](https://github.com/dniewinski/ur_modern_driver/blob/02b63f9b75806423743d23e53be423a73e51ad1c/config/ur5_controllers.yaml#L15-L23)). I'm not sure this is a big deal, since controllers will still update at 500Hz, but it did cause me to waste some time analyzing incomplete data while trying to characterize the FT sensor signals.

**Comment by IndustrialEngStudent** [comment]
Hi, I want to control the ur5e robot by first trying the test_move.py script from the universal_robot package. I am not sure how to clone the ur_moder_driver and universal_robot fork, should I clone the ur_e branch or the kinetic(-devel)? 
I am using the ROS kinetic distro. 
Then, if I "`git clone ..`" the two forks from dniewinski (and build & source), should I be able to run :` rosrun ur_modern_driver test_move.py`, or are there more changes to be made?

**Comment by miguelprada** [comment]
@IndustrialEngStudent first of all, please do not post general _how do I..._ type questions on pull request discussions such as this. These type of questions are better posted in [ROS Answers](https://answers.ros.org/questions/).

You should only need to clone the `dniewinski/kinetic-devel` branch into your workspace. Installing `universal_robot` from the binaries already includes the URe models and is the recommended way.

**Comment by IndustrialEngStudent** [comment]
@miguelprada will do, thank you

**Comment by martimorta-wood** [comment]
Hi, I am not sure if this should be said here, (the fork doesn't have issues), but here you go.
Trying the low_bandwidth_trajectory_follower I found out it didn't work in a UR10e because the firmware version is 5.x and not 3.x. I have got over this issue and the driver worked well changing an equal to to a bigger than in factory.h line 76. as shown below:
```cpp
  bool isVersion3()
  {
    return major_version_ >= 3;
  }
```
If you think this won't cause problems somewhere else I am happy to send a pull request to @dniewinski 's fork.

**Comment by yangbenbo** [comment]
Hi @dniewinski ,I have done some work after @happygaoxiao .I have also modified the
loop_hz and publish_rate in [ur5_controllers.yaml](https://github.com/ros-industrial/ur_modern_driver/blob/master/config/ur5_controllers.yaml) file to 500.Then I launch ur5e_ros_control.launch.
I use pos_based_pos_traj_controller/follow_joint_trajectory to control URe simulator.Here is my position tracking result, along with a z-direction sine trajectory. Other directions and orientations are constant. The servoj is sent at 500Hz.Sometimes I get error:No trajectory defined at current time. Please contact the package maintainer
tracking
The first picture is tracking result.The second is the time internal between send goals.As you can see,the robot is shaking.Then I uncomment line 131st in [trajectory_follower.cpp](https://github.com/dniewinski/ur_modern_driver/blob/kinetic-devel/src/ros/trajectory_follower.cpp) ,I find that when the robot is stuck,the servoj just sent the same position.I have sent the goal,but the servoj didn't get or send the goal.

image

When I change the  loop_hz and publish_rate in ur5_controllers.yaml file to 250.Everything works fine.
tracking1
I want to use 500Hz,could you please give me some advices?

**Comment by yangbenbo** [comment]
My last problem has been solved, it's just about CPU performance. Ros_control can run very well with intel i5 8400, not with AMD Ryzen 5 2400 or intel i5 6500, so next time when you need to have real-time control on the ur5e, you should have a better CPU.
There is an another question, I find when I use ros_control, I cann't use /ur_driver/URScript  topic to control io. Just  as below. Is there any solution?

image

**Comment by gavanderhoorn** [comment]
As we've officially deprecated `ur_modern_driver`, I'm closing this PR. Please refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

@dniewinski: a huge thanks for your original work on getting `ur_modern_driver` compatible with e-series controllers :+1: . It has been used by quite a few users here, while we were waiting on the official release of `ur_robot_driver`.

To all who have commented here: I would strongly recommend you migrate to `ur_robot_driver`, as it is officially supported by UR, includes support for all CB3 and e-series robots with up-to-date Polyscope versions and provides an enhanced user experience when configuring the controller to work with ROS.

**Pull request closed without merging**
