### PR TITLE
Upstream source tests

### PR DESCRIPTION
**Pull request by miguelprada**
Add a set of checks against a source checkout of `universal_robot` repo in `kinetic`.

See #266.

### CODE REVIEW

**Comment by miguelprada** [comment]
A couple of jobs demonstrating the intended effect:

- https://travis-ci.org/miguelprada/ur_modern_driver/builds/501429852
- https://travis-ci.org/miguelprada/ur_modern_driver/builds/501431277

**Comment by gavanderhoorn** [comment]
Thanks. This is indeed what I had in mind.

Remaining issue is: the regular tests are going to fail (as #266 describes), so GH will block merging by anyone except admins (at least with the current repository settings).

I'm not against giving people admin rights, but it also means that merges will look like they were "forced" by an admin overriding CI results.

**Comment by miguelprada** [comment]
Not sure there's much alternative, other than allowing the other tests to fail, and only requiring the "new ones". Not ideal, but shouldn't be discarded.

Is this handled differently in the buildfarm jobs? Not familiar enough with how that works. Can e.g. `universal_robot` be bloomed so that `ur_modern_driver` jobs can be tested against the _release candidate_ in the shadow-fixed repo?

**Comment by gavanderhoorn** [comment]
> Is this handled differently in the buildfarm jobs? Not familiar enough with how that works. Can e.g. `universal_robot` be bloomed so that `ur_modern_driver` jobs can be tested against the _release candidate_ in the shadow-fixed repo?

Releases of `ur_modern_driver` would fail in the exact same way: packages are only built against released versions of other packages.

**Comment by miguelprada** [comment]
So are configurations such as this one always require two syncs in order to add a feature that requires changes in both repositories? I must say I'm surprised there's no workaround for that.

**Comment by gavanderhoorn** [comment]
No, the buildfarm builds against `shadow-fixed`.

**Comment by miguelprada** [comment]
Ok. Getting sidetracked here, though.

About the original matter. What would you like to do?

**Comment by miguelprada** [comment]
So, should we merge this as is? What do you think, @gavanderhoorn? Would you like anything else to be discussed/added to this PR?

**Comment by gavanderhoorn** [comment]
The only way I see -- or at least without custom Travis scripts -- this work without having to merge PRs that fail CI would be to add all "standard" build tests to the "allowed to fail" part of the matrix, and to make the builds that use upstream of `universal_robot` required to pass.

I'm open to suggestions for other approaches, but I'm not sure there are any: if a PR depends on a feature not yet merged into `universal_robot` (and has seen a release) it will fail the CI builds that use binary packages.

**Comment by miguelprada** [comment]
> The only way I see this work without having to merge PRs that fail CI -- or at least without custom Travis scripts -- would be to add all "standard" build tests to the "allowed to fail" part of the matrix, and to make the builds that use upstream of universal_robot required to pass.

Mee too. I'll let you either merge this as it is, or close it and assume we either "force merge" some PRs or wait for required features of `universal_robot` to be released.

**Comment by gavanderhoorn** [comment]
@miguelprada: I decided to squash-merge this, as the your commit was essentially a "trial".

Thanks for the PR and let's keep an eye on whether this actually works satisfactorily.

**Pull request merged**
