### PR TITLE
UR e-series 5.4 and 3.10 compatibility update

### PR DESCRIPTION
**Pull request by AdmiralWall**
Modified ur_modern_driver to be compatible with UR e-series robots running 5.4 or 3.10 software. This driver should be backwards compatible with previous software versions. The README has been updated to reference e-series launch files and potential solutions to problems with excessive joint movements in planning and overshooting in execution. 

This has been successfully tested on a UR10e robot running 5.4.2.76197 software with both kinetic and melodic ROS installs. This works with ros_industrial's universal_robot. 

Should fix issues #316 and #136 and expands on #216 .

### CODE REVIEW

**Comment by juanojun** [comment]
hello,
i have a problem when trying to run UR3e with the ur3e_bringup.launch that was posted above
the detail is just like in the picture
can i get somehelp with this?
currently using ubuntu 16.04 LTS
UR software version is 5.4
Rosdistro : Kinetic

**Comment by AdmiralWall** [comment]
@juanojun have you tried the ur3e_bringup_joint_limited.launch yet? And can I see your terminal commands to launch?

**Comment by juanojun** [comment]
this is the command for the ur3e_bringup.launch that i used.
and fyi, robot's ip : 192.168.1.102 and pc's ip : 192.168.1.101
bringup_command
bringup_command02
bringup_command03

**Comment by juanojun** [comment]
also for the ur3e_bringup_joint_limited the similar problem happens too
joint_limited
joint_limited02

**Comment by gavanderhoorn** [comment]
@juanojun: please don't post screenshots of terminals. It's all text, so just copy-paste it into the comment.

As to your problem: `-11` is a `SEGFAULT`, so it would appear something is trying to access memory it should not (fi: `nullptr` dereference or something similar).

**Comment by juanojun** [comment]
i'm so sorry for screenshoots posting.
so how can i solve that type of error?

**Comment by gavanderhoorn** [comment]
> so how can i solve that type of error?

Most straightforward would be to:

 - build the driver in debug mode
 - run it in a debugger (`gdb` or similar)

That should tell you *where* the `SEGFAULT` is happening.

At that point it would come down to figuring out *what* is causing it.

**Comment by juanojun** [comment]
Thank you so much. now the problem is solved and the robot is moving!

**Comment by gavanderhoorn** [comment]
> Thank you so much. now the problem is solved and the robot is moving!

It would be good to know what in the end was the problem.

**Comment by tanyouliang95** [comment]
I tried this fork `ur_modern_driver` with a UR10e arm, It works for me with Moveit. Thanks for the contribution! :+1:

**Comment by AdmiralWall** [comment]
@gavanderhoorn what do you need from me to be able to have this merged?

**Comment by Ruthy85** [comment]
I am facing the same issue. Based on the workaround, I will proceed to install melodic (now working with kinetic) and do the same testing. Any update available for kinetic? Thanks

**Comment by gavanderhoorn** [comment]
There is nothing in here that will work differently under Melodic or Kinetic.

**Comment by Ruthy85** [comment]
Ok, so I am facing the same issue and this is not clear for me what was the solution for @juanojun.
Any solution?

**Comment by gavanderhoorn** [comment]
You mention "the same issue", but it's unclear to me what problem you have.

**Comment by Ruthy85** [comment]
Sure, sorry. Same error but with an UR5e:

[ INFO] [1570010886.400587842]: Setting up connection: 172.196.0.11:30002
[ INFO] [1570010886.400766029]: Setting up connection: 172.196.0.11:30003
[ INFO] [1570010886.401881688]: Connection established for 172.196.0.11:30002
[ INFO] [1570010886.402106113]: Connection established for 172.196.0.11:30003
[ INFO] [1570010886.403273885]: Starting ActionServer
[ INFO] [1570010886.403399694]: Trajectory thread started
[ERROR] [1570010886.429175180]: Sub-package of type 3 was not parsed completely!
[ INFO] [1570010886.429227347]: Disconnecting from 172.196.0.11:30002
[ INFO] [1570010886.429316624]: Shutting down on stopped pipeline StatePacket
[ur_driver-3] process has died [pid 12890, exit code 1, cmd /home/ros/catkin_ws/devel/lib/ur_modern_driver/ur_driver __name:=ur_driver __log:=/home/ros/.ros/log/8628b2d6-e4fc-11e9-b4b3-08002750fd6a/ur_driver-3.log].
log file: /home/ros/.ros/log/8628b2d6-e4fc-11e9-b4b3-08002750fd6a/ur_driver-3*.log

**Comment by gavanderhoorn** [comment]
My advice would still be the same as what I wrote in https://github.com/ros-industrial/ur_modern_driver/pull/339#issuecomment-529816118.

**Comment by juanojun** [comment]
in my case, when i run in debug mode i notice i missed some lines when merging kinetic-devel branch just like in here
https://github.com/ros-industrial/ur_modern_driver/commit/c691f6f019518f233a5996aa7ccaed826ce46352
after i add those lines, the problem is fixed

**Comment by Ruthy85** [comment]
> in my case, when i run in debug mode i notice i missed some lines when merging kinetic-devel branch just like in here
> [c691f6f](https://github.com/ros-industrial/ur_modern_driver/commit/c691f6f019518f233a5996aa7ccaed826ce46352)
> after i add those lines, the problem is fixed

Thanks. I triple check it but all seems equal. I am following with the @gavanderhoorn advice.

**Comment by gavanderhoorn** [comment]
I'm still confused (perhaps even more so).

@juanojun wrote:
> in my case, when i run in debug mode i notice i missed some lines when merging kinetic-devel branch just like in here
> [c691f6f](https://github.com/ros-industrial/ur_modern_driver/commit/c691f6f019518f233a5996aa7ccaed826ce46352)
> after i add those lines, the problem is fixed

Which particular version are you running/debugging?

Can you point to a commit?

The commit you linked is a merge commit, which merges just about everything in `kinetic-devel` into this PR. If that would be 'missing', I doubt you'd be able to build the code.

**Comment by Ruthy85** [comment]
I was running the cloned version from [AdmirallWall](https://github.com/AdmiralWall/ur_modern_driver.git).
And then I tested the merge changes from c691f6f and same error.

**Comment by Ruthy85** [comment]
Finally I have it running. I create a fresh ubuntu install and set everything necessary to run the AmiralWall merge into kinetic-devel. Thank you.
Now I have the pose of the real robot and moveit ready for the planning.
I am getting always Failed plan and the trace is:
You can start planning now!

[ INFO] [1570454211.959254809]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ WARN] [1570454211.959419965]: Joint 'wrist_1_joint' from the starting state is outside bounds by a significant margin: [ 4.68739 ] should be in the range [ -3.14159 ], [ 3.14159 ] but the error above the ~start_state_max_bounds_error parameter (currently set to 0.1)
and other errors follow...

Rviz shows the position of the real robot and is also refreshed when I move the robot manualy. However, it seems the that the pose values are out of range... What could be the problem?

**Comment by Ruthy85** [comment]
If I launch the ur5e_bringup (without joint limited), I can successfuly do the Plan.
However, when executing, no messages are displayed in the console and the robot is not moving.
The same if I Plan and Execute.
Plan is perform successfuly but after Execute, remains as:

```
[ INFO] [1570533611.950428269]: SimpleSetup: Path simplification took 0.095551 seconds and changed from 3 to 2 states
[ INFO] [1570533617.498493393]: Received new trajectory execution service request...
```
Am I missing anything? Thank you

**Comment by AdmiralWall** [comment]
I apologize for a late response, @Ruthy85 . If execute isn't working, do you have Remote Control turned on the TeachPad?

**Comment by Ruthy85** [comment]
Yes, everything is fine, thank you for your reply. I was not setting the action servers properly.

**Comment by AdmiralWall** [comment]
I am glad to hear it!

**Comment by gavanderhoorn** [comment]
I'm closing this as we've officially deprecated this package.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629).

**Comment by gavanderhoorn** [comment]
@AdmiralWall: thank you very much for submitting this PR to improve compatibility of `ur_modern_driver` with newer version of Polyscope and e-series controllers.

However, as `ur_robot_driver` has been released, we've decided to not merge any PRs here that would improve `ur_modern_driver`'s compatibility with CB3 or e-series controllers.

If you still have the need, I would encourage you to use `ur_robot_driver` with your robot(s).

**Comment by gavanderhoorn** [comment]
@robinsonmm.

**Comment by AdmiralWall** [comment]
@gavenderhoorn you are very welcome. I'm glad to hear ur_robot_driver is done and working!

**Pull request closed without merging**
