### PR TITLE
Add robot_status support

### PR DESCRIPTION
**Pull request by matEhickey**
Hello Thomas,  
Here is my first pull-request, so don't hesitate to ask me to modify things.  
The modifications here only consist of a RobotStatus [http://docs.ros.org/kinetic/api/industrial_msgs/html/msg/RobotStatus.html](url) publisher, allowing ur_modern_driver to come closer to ros-industrial specs.  
It's now publishing every 100ms, but may need to be modified.  
I also have a problem, I'm now unable to properly close the script, or to get error on close, because of the python-urx Robot module (I suspect the connection).

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Hi @matEhickey. Very nice to see that you considered opening a PR for what we discussed on [ROS Answers](https://answers.ros.org/question/272869). :+1: 

This functionality is definitely something we want to add to `ur_modern_driver`, but I feel we could adapt your approach a bit and make it much less of an invasive change.

As far as I can tell, all (most?) the info you are now getting access to by using `urx` is available already in the `RobotState` class:

https://github.com/ThomasTimm/ur_modern_driver/blob/6c3cade12fb47f41b816d05377feaea993742a28/include/ur_modern_driver/robot_state.h#L196-L202

Those functions are backed by the same datastream that `urx` uses to get you that info. To avoid introducing the `urx` (and Python) dependency, it would be great if you could change your implementation use those functions.

If I understand your current PR, I think you should be able to get away with just adding a new `ros::Publisher` to the `RosWrapper` for the `industrial_msgs::RobotStatus` msg, and then populating and publishing it in `RosWrapper::publishMbMsg()` (somewhere around [here](https://github.com/ThomasTimm/ur_modern_driver/blob/6c3cade12fb47f41b816d05377feaea993742a28/src/ur_ros_wrapper.cpp#L637)). Note that `urx`'s `robot.secmon` is called `robot_.sec_interface` in the `RosWrapper` class, so it's essentially the same.

It's not Python, but I believe you'll find the implementation to be significantly fewer lines.

That is not necessarily less work for you, but it is for us maintainers in the future, as we then don't have to also maintain a Python script and dependency (ie: keep track of `urx`).

**Comment by matEhickey** [comment]
Hello, I just did the change. Thanks for the directions.  
Do you need me to re-begin a pull request to preserve the commit history on ur_common file ? (as I modified it, but restore it on the newest commit )

**Comment by gavanderhoorn** [comment]
Thanks, much appreciated 👍.

re: history: I would suggest you squash all your changes into a single commit (don't forget to update the commit msg), and force push that. That will automatically overwrite the commits in this PR.

No need to open a new one.

**Comment by matEhickey** [comment]
I think that it's good now, can you confirm me ?

**Comment by gavanderhoorn** [comment]
The commit history now looks ok.

minor: you might want to check the email address that was used for the commit. It currently just says `mathias`.

**Comment by gavanderhoorn** [comment]
I'll do a proper review later.

**Comment by matEhickey** [comment]
I think the email address is now set, but I'm not sure

**Comment by gavanderhoorn** [comment]
This was (still is) a very nice PR @matEhickey. It got ported to the new "kinetic refactor" by @simonschmeisser in the @Zagitta fork and merged into that in 24eef75d726924687e606e672fbfc3f5d741a4c8.

As we're not merging new features in the `master` branch, I'll close this PR, but know that your work is part of the `kinetic-devel` version.

So thanks again :+1: for the PR.

**Comment by matEhickey** [comment]
👍

**Pull request closed without merging**
