### PR TITLE
General cleanup of build script and package manifest

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Summary:

 - updated maintainers and authors section
 - removed all boilerplate comments
 - made `catkin_lint` happier (sorting lists, adding missing dependency declarations, etc)
 - upgraded manifest to format 2

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Dependency declarations could do with some more TLC, but we'll do that at a later time.

**Comment by gavanderhoorn** [comment]
@ipa-nhg fyi.

Could I ask you to also review this PR?

**Comment by ipa-nhg** [comment]
@gavanderhoorn LGTM :+1:  
thanks!

P.S. Tested locally, with travis_ci and catkin_lint. The only missed thing is a install tag for the `test_move.py` script, but I think this is intended.

**Comment by gavanderhoorn** [comment]
> The only missed thing is a install tag for the `test_move.py` script, but I think this is intended.

yes.

I'm currently not planning to also `install(..)` the test script, hence no install rule.

**Comment by gavanderhoorn** [comment]
Thanks for the review.

**Pull request merged**
